Repository reactor/reactor-netty, pull requests merged in 2019-07, with the labels that each got.

#769 Add NettyOutbound.send/sendObject API with a predicate for enforcing flush operation
  src/main/java/reactor/netty/NettyOutbound.java
  src/main/java/reactor/netty/ReactorNetty.java
  src/main/java/reactor/netty/channel/ChannelOperations.java
  src/main/java/reactor/netty/channel/MonoSend.java
  src/main/java/reactor/netty/channel/MonoSendMany.java
  src/main/java/reactor/netty/http/HttpOperations.java
  src/test/java/reactor/netty/NettyOutboundTest.java
  src/test/java/reactor/netty/channel/MonoSendManyTest.java
Labels: enhancement

#787 Documentation fix for error: "neither SslContextBuilder nor SslContext is specified"
  src/docs/asciidoc/http-server.adoc
Labels: bug, documentation

#799 Deprecate FutureMono#deferFutureWithContext
  src/main/java/reactor/netty/FutureMono.java
Labels: deprecation
