Repository reactor/reactor-netty, pull requests merged in 2019-09, with the labels that each got.

#848 Avoid calling `Pool.close()` which may block reactor thread permanently.
  src/main/java/reactor/netty/resources/PooledConnectionProvider.java
Labels: type/bug

#855 Add proxy protocol auto detect feature.
  src/main/java/reactor/netty/http/server/HAProxyMessageDetector.java
  src/main/java/reactor/netty/http/server/HttpServer.java
  src/main/java/reactor/netty/http/server/ProxyProtocolSupportType.java
  src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/enhancement, warn/deprecation

#862 resolve the errorprone warning.
  src/main/java/reactor/netty/ReactorNetty.java
  src/main/java/reactor/netty/channel/BootstrapHandlers.java
  src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  src/main/java/reactor/netty/channel/MonoSendMany.java
  src/main/java/reactor/netty/http/HttpOperations.java
  src/main/java/reactor/netty/http/client/HttpClientConnect.java
  src/main/java/reactor/netty/http/client/HttpClientOperations.java
  src/main/java/reactor/netty/http/server/ConnectionInfo.java
  src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
  src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  src/main/java/reactor/netty/tcp/TcpServerBind.java
Labels: type/enhancement
