Repository reactor/reactor-netty, pull requests merged in 2022-01, with the labels that each got.

#1989 fixes #1940: adds support to basic auth (username and password) to pr…
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ProxyProviderTest.java
Labels: type/enhancement

#1994 Prevent error when trying to add IdleTimeout
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
Labels: type/bug

#1997 Release notes configuration
  .github/release.yml
Labels: type/chore

#1999 [doc] Separate connection pool documentation
  docs/asciidoc/http-client-conn-provider.adoc
  docs/asciidoc/http-client.adoc
  docs/asciidoc/tcp-client-conn-provider.adoc
  docs/asciidoc/tcp-client.adoc
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/pool/config/Application.java
Labels: type/documentation

#1998 HttpServerOperations#isFormUrlencoded handles header value with charset
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2005 Remove japicmp exclusions
  reactor-netty-core/build.gradle
  reactor-netty-http/build.gradle
Labels: type/chore

#1996 [build] Hardening of GitHub actions
  .github/workflows/check_netty_snapshots.yml
  .github/workflows/check_transport.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish.yml
Labels: type/chore

#2002 Ensure the correct Context is provided to ContextAwareHttpServerMetricsRecorder
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#1981 Document that extended TCP keep-alive settings are only available on …
  docs/asciidoc/http-client.adoc
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/channeloptions/Application.java
Labels: type/documentation

#2008 Update to netty-tcnative-boringssl-static v2.0.48.Final
  build.gradle
Labels: type/dependency-upgrade

#2007 [doc] Add info for TCP keep-alive conf on various loadbalancers that may cause connection closed
  docs/asciidoc/faq.adoc
Labels: type/documentation
