Repository reactor/reactor-netty, pull requests merged in 2022-12, with the labels that each got.

#2598 Ensure the connection is closed at the end of the test
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Labels: type/chore

#2595 Ensure `Reactor Context` injected with `HttpClient#mapConnect` is available on send request/receive response
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFinalizer.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug

#2605 Update documentation for `ConnectionProvider.Builder#disposeInactivePoolsInBackground`
  docs/asciidoc/http-client-conn-provider.adoc
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
Labels: type/documentation

#2607 Add test for `ConnectionProvider.Builder#disposeInactivePoolsInBackground`
  reactor-netty-http/build.gradle
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/chore

#2608 Deregister connection pool metrics from Micrometer (or alternate registry) when disposing the connection pool
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttp2ConnectionProviderMeterRegistrar.java
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
Labels: type/enhancement

#2609 PRs with label `type/test` go to `Documentation, Tests and Build` section
  .github/release.yml
Labels: type/chore

#2610 Update `ConnectionProvider.MeterRegistrar` javadoc
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
Labels: type/documentation

#2611 Depend on `Netty` `v4.1.86.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2613 Remove default implementation for `ConnectionProvider.MeterRegistrar#deRegisterMetrics`
  reactor-netty5-core/src/main/java/reactor/netty5/resources/ConnectionProvider.java
  reactor-netty5-core/src/test/java/reactor/netty5/resources/ConnectionProviderTest.java
  reactor-netty5-http/src/noMicrometerTest/java/reactor/netty5/http/client/HttpClientNoMicrometerTest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientTest.java
Labels: warn/api-change

#2612 Depend on `Netty QUIC Codec` `v0.0.35.Final`
  build.gradle
Labels: type/enhancement
