Repository reactor/reactor-netty, pull requests merged in 2022-08, with the labels that each got.

#2413 Introduce HttpClientProxyProvider with HTTP related configurations
  reactor-netty5-core/src/main/java/reactor/netty5/transport/ClientTransport.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/ProxyProvider.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/ProxyProviderTest.java
  reactor-netty5-http/build.gradle
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClient.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientProxyProvider.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientProxyProviderTest.java
Labels: type/enhancement

#2416 Update reference documentation for UDS support
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
Labels: type/enhancement

#2414 Ensure HttpServer#idleTimeout configuration is applied for both HTTP/1.1 and HTTP/2
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/IdleTimeoutHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/bug

#2391 Revise HttpMetricsHandlerTests and fix testServerConnectionsRecorder
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#2417 Rename AdvancedByteBufFormat to AdvancedBufferFormat
  docs/asciidoc/wire-logger.adoc
  reactor-netty5-core/src/main/java/reactor/netty5/tcp/SslProvider.java
  reactor-netty5-core/src/main/java/reactor/netty5/tcp/TcpClientConfig.java
  reactor-netty5-core/src/main/java/reactor/netty5/tcp/TcpServerConfig.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/ProxyProvider.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/Transport.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/logging/AdvancedBufferFormat.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/logging/ReactorNettyLoggingHandler.java
  reactor-netty5-core/src/main/java/reactor/netty5/udp/UdpClientConfig.java
  reactor-netty5-core/src/main/java/reactor/netty5/udp/UdpServerConfig.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/TransportTest.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/logging/AdvancedBufferFormatTest.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/logging/ReactorNettyLoggingHandlerTest.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/client/wiretap/custom/Application.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/server/wiretap/custom/Application.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/tcp/client/wiretap/custom/Application.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/tcp/server/wiretap/custom/Application.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/udp/client/wiretap/custom/Application.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/udp/server/wiretap/custom/Application.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientConfig.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerConfig.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/ConnectionPoolTests.java
Labels: type/enhancement

#2420 Upgrade to Gradle v7.5.1
  gradle/wrapper/gradle-wrapper.properties
Labels: type/dependency-upgrade

#2422 Update Micrometer dependencies
  build.gradle
Labels: type/enhancement

#2423 Update to netty-tcnative-boringssl-static v2.0.54.Final
  build.gradle
Labels: type/dependency-upgrade

#2424 [test] Adapt to the changes in AbstractChannel
  reactor-netty5-core/src/test/java/reactor/netty5/ReactorNettyTest.java
Labels: type/enhancement

#2434 [test] Adapt to the changes in AbstractChannel
  reactor-netty5-core/src/test/java/reactor/netty5/ReactorNettyTest.java
Labels: type/enhancement

#2433 ServerTransport.Acceptor#exceptionCaught should not propagate the event
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
Labels: type/enhancement

#2432 Add reflection hints for better native-image support
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-core/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-core/reflect-config.json
  reactor-netty-core/src/test/java/reactor/netty/NativeConfigTest.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
  reactor-netty-http/src/test/java/reactor/netty/NativeConfigTest.java
Labels: type/enhancement

#2435 Propagate the Observation only when metrics are enabled
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
Labels: type/enhancement

#2421 HttpMetricsHandlerTests testServerConnectionsMicrometer still unstable
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#2437 Ensure ChannelGroup and associated Executor are closed
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2447 [test] Use crafted Appender instead of mocking
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/enhancement

#2449 [test] Adapt to the changes in AbstractChannel
  reactor-netty5-core/src/test/java/reactor/netty5/ReactorNettyTest.java
Labels: type/enhancement

#2448 Do not add io.netty:netty5-resolver-dns-native-macos:osx-x86_64 as required dependency
  reactor-netty5-core/build.gradle
  reactor-netty5-http/build.gradle
Labels: type/enhancement

#2457 Use Netty contribs from main branches
  .github/workflows/check_transport.yml
Labels: type/enhancement
