Repository reactor/reactor-netty, pull requests merged in 2022-03, with the labels that each got.

#2063 Ensure server connections metrics are not reported for the client
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#2064 [test] Refactor the test in order to be able to test H2/H2C variations
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpsMetricsHandlerTests.java
Labels: type/enhancement

#2069 Update Reactor Core version to 3.5.0-SNAPSHOT
  gradle.properties
Labels: type/chore

#2057 Reduce memory overhead when creating Micrometer timers
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyHandlerContext.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTimerObservationHandler.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/MicrometerSslReadHandler.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java
Labels: type/enhancement

#2071 Deprecated Connection#addHandler(...)
  reactor-netty-core/src/main/java/reactor/netty/Connection.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/lifecycle/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/lifecycle/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/lifecycle/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/lifecycle/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client/lifecycle/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/lifecycle/Application.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/channel/ChannelOperationsHandlerTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: warn/deprecation

#2076 [tests] Switch to ChannelHandlerAdapter
  reactor-netty-core/src/test/java/reactor/netty/ConnectionTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/enhancement

#2078 Wrong metric value for TLS handshake time
  reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
Labels: type/bug

#2082 [doc] Extend the example for disabling the connection pool
  docs/asciidoc/http-client-conn-provider.adoc
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/pool/Application.java
Labels: type/documentation

#2081 Remove TODOs related to caching Timers
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/chore

#2085 Update plugin japicmp to v0.4.0
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-http-brave/build.gradle
  reactor-netty-http/build.gradle
Labels: type/dependency-upgrade

#2066 Enable HttpClient/HttpServer metrics when protocol is H2/H2C
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/enhancement

#2092 Upgrade to Gradle v7.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: type/chore

#2097 Update to Netty v4.1.75.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/dependency-upgrade

#2098 Ensure the Pool implementation for the test class implements the new abstract method config()
  reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/chore

#2093 Ensure all cases, when Http2FrameCodec is not available, are handled properly
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
Labels: type/bug

#2099 Update netty-incubator-transport-native-io_uring to v0.0.13.Final
  build.gradle
Labels: type/dependency-upgrade

#2090 Optimize Http2Pool by reducing calls to CLDQ size method
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
Labels: type/enhancement

#2100 Update to netty-tcnative-boringssl-static v2.0.51.Final
  build.gradle
Labels: type/dependency-upgrade

#2103 Update Micrometer dependency to version 2.0.0-M3
  build.gradle
Labels: type/enhancement

#2051 Added context propagation from caller thread/reactor context
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/observability/contextpropagation/propagator/ChannelContextContainerPropagator.java
  reactor-netty-core/src/main/java/reactor/netty/observability/contextpropagation/propagator/ReactorContextContainerPropagator.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/main/resources/META-INF/services/io.micrometer.contextpropagation.ContextContainerPropagator
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/enhancement

#2107 Redundant throws clause
  reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java
Labels: type/chore

#2108 Statement lambda is replaced with expression lambda
  reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportResolverHooksTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/chore

#2109 Remove explicit type argument
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
Labels: type/chore

#2112 Remove the usage of the deprecated currentContext() in MonoSink
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/test/java/reactor/netty/resources/NewConnectionProviderTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConnect.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicOperations.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServerBind.java
Labels: type/chore

#2118 Move to the new micrometer-observation module
  build.gradle
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMeters.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTimerObservationHandler.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProviderMeters.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMeters.java
  reactor-netty-core/src/main/java/reactor/netty/transport/EventLoopMeters.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyHttpClientTracingObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyHttpServerTracingObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/enhancement

#2119 [test] Do not use Thread.sleep(1000) but check the results once the last stream is closed
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
Labels: type/enhancement

#2104 Make metric tests faster
  reactor-netty-http/src/test/java/reactor/netty/CustomBlockHoundIntegration.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2120 Ensure channel promises support listeners when SOCKS proxy handler is used
  reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
Labels: type/bug

#2126 Update jacoco tool version to 0.8.7
  build.gradle
Labels: type/dependency-upgrade

#2127 [test] Remove maxGranularity in order to see parameterized tests failures
  build.gradle
Labels: type/chore

#2129 Update Micrometer Docs Generator to 1.0.0-SNAPSHOT
  build.gradle
Labels: type/enhancement

#2133 [test] Run the test with a dedicated MeterRegistry
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/chore

#2134 [test] Handle use cases when Reactor Netty version is milestone or release candidate
  reactor-netty-core/src/jarFileTest/java/reactor/netty/JarFileShadingTest.java
Labels: type/chore

#2135 Upgrade to Gradle v7.4.2
  gradle/wrapper/gradle-wrapper.properties
Labels: type/chore
