Repository reactor/reactor-netty, pull requests merged in 2022-10, with the labels that each got.

#2522 Bump Netty QUIC Codec to v0.0.33.Final
  build.gradle
Labels: type/enhancement

#2523 Enable CodeQL for netty5 branch
  .github/workflows/codeql-analysis.yml
Labels: type/chore

#2461 Leak detection properties are added for the test execution
  build.gradle
  reactor-netty5-core/src/main/java/reactor/netty5/NettyOutbound.java
  reactor-netty5-core/src/main/java/reactor/netty5/ReactorNetty.java
  reactor-netty5-core/src/test/java/reactor/netty5/NettyOutboundTest.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientConfig.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerConfig.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/SimpleCompressionHandler.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/WebsocketServerOperations.java
  reactor-netty5-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty5-http/reflect-config.json
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientOperationsTest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/logging/AccessLogHandlerH1Tests.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/logging/AccessLogHandlerH2Tests.java
Labels: type/enhancement

#2528 Check for log level
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/AddressResolverGroupMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
Labels: type/chore

#2529 Ensure logs are prefixed with channel information when possible
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
Labels: type/chore

#2526 Update Micrometer dependencies to 1.10.0-SNAPSHOT before RC1
  build.gradle
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMeters.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProviderMeters.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMeters.java
  reactor-netty-core/src/main/java/reactor/netty/transport/EventLoopMeters.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/enhancement

#2530 Add missing package-info.java
  reactor-netty-core/src/main/java/reactor/netty/internal/util/package-info.java
  reactor-netty-core/src/main/java/reactor/netty/transport/logging/package-info.java
Labels: type/chore

#2524 Use BufferAllocator#compose(...) for creating CompositeBuffer
  reactor-netty5-core/src/main/java/reactor/netty5/BufferFlux.java
  reactor-netty5-core/src/main/java/reactor/netty5/BufferMono.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
Labels: type/enhancement

#2531 Deprecate ReactorNetty#toPrettyHexDump
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
Labels: warn/deprecation

#2532 Remove deprecated ReactorNetty#toPrettyHexDump
  reactor-netty5-core/build.gradle
  reactor-netty5-core/src/main/java/reactor/netty5/ReactorNetty.java
Labels: type/enhancement

#2533 Temporary disable the check for KQueue as there is issue with MacOS natives
  reactor-netty5-core/src/test/java/reactor/netty5/resources/DefaultLoopResourcesTest.java
Labels: type/chore

#2535 Migrate to the new micrometer-docs-generator
  gradle/asciidoc.gradle
Labels: type/enhancement

#2536 Deprecate Cookie encoder/decoder settings
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: warn/deprecation

#2538 Update Micrometer dependencies to 1.10.0-RC1
  build.gradle
Labels: type/enhancement

#2539 Avoid NPE in AbstractHttpClientMetricsHandler write listener
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java
Labels: type/bug

#2547 Remove transitive dependency netty5-codec-http from reactor-netty5-core
  reactor-netty5-core/build.gradle
  reactor-netty5-core/src/main/java/reactor/netty5/transport/ClientTransport.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/ProxyProvider.java
  reactor-netty5-core/src/test/java/reactor/netty5/ConnectionTest.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/ClientTransportTest.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/ProxyProviderTest.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClient.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientProxyProvider.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/ClientTransportTest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientProxyProviderTest.java
Labels: type/enhancement

#2548 Suppress NarrowingCompoundAssignment warnings
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java
Labels: type/chore

#2441 ensures flux receiver terminates subscriber on dispose
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2550 Small refactoring in FluxReceive
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
Labels: type/enhancement

#2551 Once the response is sent ensure no other attempt to send a new response
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpTrafficHandler.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
Labels: type/enhancement

#2555 Ensure Reactor Netty follows the requirements for span name and tags
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyPropagatingReceiverTracingObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyPropagatingSenderTracingObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/enhancement

#2556 Fix memory leak in HttpClient#sendForm for file uploads with streams
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFormEncoder.java
Labels: type/bug
