Repository reactor/reactor-netty, pull requests merged in 2022-09, with the labels that each got.

#2460 Update to Netty v4.1.80.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2464 Replace Buffer/ByteBufHolder#touch with Resource#touch
  reactor-netty5-core/src/main/java/reactor/netty5/channel/FluxReceive.java
Labels: type/enhancement

#2469 Add conditions to the reflect-config.json
  reactor-netty-core/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-core/reflect-config.json
  reactor-netty-core/src/test/java/reactor/netty/NativeConfigTest.java
  reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
  reactor-netty-http/src/test/java/reactor/netty/NativeConfigTest.java
Labels: type/enhancement

#2472 Update to Netty v4.1.81.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2470 Adapt SampleTestRunner change in micrometer tracing
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/enhancement

#2476 Update Netty QUIC Codec to v0.0.30.Final
  build.gradle
Labels: type/dependency-upgrade

#2477 Bump netty-incubator-transport-native-io_uring
  build.gradle
Labels: type/dependency-upgrade

#2478 Update Micrometer dependencies
  build.gradle
Labels: type/enhancement

#2482 Update to Netty v4.1.82.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2483 Ensure HttpClientConfig#connectionProvider returns the original provider used to create HttpClient
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpConnectionProviderTest.java
Labels: type/bug

#2489 Update Micrometer dependency to version 1.10.0-M6
  build.gradle
Labels: type/enhancement

#2495 Set the trailing headers directly when constructing DefaultLastHttpContent
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
Labels: type/enhancement

#2496 Defer the creation of the request/response object
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
Labels: type/enhancement

#2501 [test] Ensure HTTP/2 tests comply with RFC requirements for HTTP/2 headers
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderH2Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH2Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/LoggingTests.java
Labels: type/bug

#2497 Improve JapiCmp: avoid misses, improve reporting and exclusions
  .github/workflows/check_transport.yml
  reactor-netty-core/build.gradle
  reactor-netty-http-brave/build.gradle
  reactor-netty-http/build.gradle
Labels: type/chore

#2503 Adapt to the changed DefaultHttpHeaders#validateKey
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
Labels: type/enhancement

#2505 [test] Adapt to Netty change to drop the data when it is unexpected
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
Labels: type/enhancement

#2506 Fix javadoc
  reactor-netty5-core/src/main/java/reactor/netty5/transport/BufferAllocatorMeters.java
Labels: type/documentation

#2508 Remove unused code
  reactor-netty5-core/src/main/java/reactor/netty5/channel/ChannelOperations.java
  reactor-netty5-core/src/main/java/reactor/netty5/channel/MonoSend.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/BufferAllocatorMetrics.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/TransportConfig.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientConnect.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
Labels: type/enhancement

#2511 Use pattern matching for the instanceof
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientConfig.java
Labels: type/enhancement

#2510 Add the missing Nullable annotation
  reactor-netty5-core/src/main/java/reactor/netty5/udp/UdpClientConfig.java
  reactor-netty5-core/src/main/java/reactor/netty5/udp/UdpServerConfig.java
Labels: type/enhancement

#2514 [reactor-netty-http] Remove ByteBufHolder usage
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/logging/AccessLogHandlerH1.java
Labels: type/enhancement

#2515 Update to Netty v5.0.0.Alpha5
  .github/workflows/check_transport.yml
  build.gradle
Labels: type/enhancement

#2516 [reactor-netty-core] Remove ByteBufHolder usage
  build.gradle
  reactor-netty5-core/build.gradle
  reactor-netty5-core/src/main/java/reactor/netty5/ReactorNetty.java
  reactor-netty5-core/src/main/java/reactor/netty5/channel/MonoSend.java
  reactor-netty5-core/src/main/java/reactor/netty5/channel/MonoSendMany.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/logging/AdvancedBufferFormat.java
  reactor-netty5-core/src/main/java/reactor/netty5/transport/logging/ReactorNettyLoggingHandler.java
  reactor-netty5-core/src/test/java/reactor/netty5/transport/logging/ReactorNettyLoggingHandlerTest.java
  reactor-netty5-http/build.gradle
Labels: type/enhancement

#2517 BufferFlux and BufferMono do not depend on netty-codec-http anymore
  reactor-netty5-core/src/main/java/reactor/netty5/BufferFlux.java
  reactor-netty5-core/src/main/java/reactor/netty5/BufferMono.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/HttpOperations.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
Labels: type/enhancement

#2519 Update Netty Contrib version to 5.0.0.Alpha2
  .github/workflows/check_transport.yml
  .github/workflows/publish.yml
  build.gradle
Labels: type/enhancement

#2518 Close connection when a TLS close_notify is received and acknowledged.
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement
