Repository reactor/reactor-netty, pull requests merged in 2022-02, with the labels that each got.

#2012 Remove unnecessary method param
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
Labels: type/chore

#2009 Http2 streams not closed if request data is not fully consumed
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2014 Use the correct owner when invalidating the stream on close
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2StreamBridgeClientHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/bug

#2015 Additional read operation needs to be scheduled on writing LastHttpContent
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/test/java/reactor/netty/BaseHttpTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/bug

#2016 Replace MeterKey by Object key
  reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java
Labels: type/enhancement

#2017 Ensure the stream is closed immediately when a server response is received but still sending the request body
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2020 Ensure HttpClient uses the new ConnectionProvider after HttpResources#reset
  reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Resources.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpConnectionProviderTest.java
Labels: type/bug

#2023 Run spotless/japicmp as a preliminary job in ci
  .github/workflows/check_transport.yml
  reactor-netty-http-brave/build.gradle
Labels: type/chore

#2025 Update to Netty v4.1.74.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/dependency-upgrade

#2029 Propagate the client thread in the ConnectionPool subscription context
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
Labels: type/bug

#2035 Adapt the workflows to run against 1.0.x branch
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish.yml
  build.gradle
Labels: type/chore

#2036 Update Reactor Netty version to 1.1.0-SNAPSHOT
  gradle.properties
Labels: type/chore

#2038 Correct the start/end year in the copyright
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-http-brave/build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-incubator-quic/build.gradle
  reactor-netty-incubator-quic/src/test/resources/logback.xml
Labels: type/chore

#2040 Use MeterRegistryAssert for checking Timers existence
  reactor-netty-core/build.gradle
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
  reactor-netty-core/src/test/java/reactor/netty/udp/UdpMetricsTests.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/transport/AddressResolverGroupMetricsTest.java
Labels: type/enhancement

#2043 Update reactor-netty-core timers to use the new Observation
  build.gradle
  docs/asciidoc/http-client.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  docs/asciidoc/udp-client.adoc
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyHandlerContext.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/MicrometerSslReadHandler.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/AddressResolverGroupMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/enhancement

#2047 Ensure the provided event loop is not null
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
Labels: type/bug

#2045 Update reactor-netty-http timers to use the new Observation
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyHttpClientTracingObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyHttpServerTracingObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/enhancement

#2048 Create the Tags once as they are the same for every Gauge
  reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttp2ConnectionProviderMeterRegistrar.java
Labels: type/enhancement

#2049 Improve readability of preliminary how-to-fix hint in CI
  .github/workflows/check_transport.yml
Labels: type/chore

#2050 Add javadoc for the method param
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
Labels: type/documentation

#2053 Do not override the contextual name for HttpClientContext/HttpServerContext
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/enhancement

#2054 Update Netty QUIC Codec to v0.0.26.Final
  build.gradle
Labels: type/dependency-upgrade

#2055 Update to netty-tcnative-boringssl-static v2.0.50.Final
  build.gradle
Labels: type/dependency-upgrade
