Repository reactor/reactor-netty, pull requests merged in 2022-06, with the labels that each got.

#2263 Update faq for connection closed BEFORE error
  docs/asciidoc/faq.adoc
Labels: type/documentation

#2265 Ensure a custom factory can be used with HttpClient#sendForm
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFormEncoder.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java
Labels: type/bug

#2268 Update Reactive Streams javadoc to version 1.0.4
  build.gradle
Labels: type/documentation

#2270 ReactorNettyLoggingHandler to use BufferFormat
  reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
Labels: type/enhancement

#2271 AbstractChannelMetricsHandler works now only with Buffer
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
Labels: type/enhancement

#2272 Adapt to the new ChannelFactory/ServerChannelFactory
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoop.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNIO.java
  reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpResources.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerConfig.java
Labels: type/enhancement

#2273 Adapt TransportConnector to the changes in channel.register()
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
Labels: type/enhancement

#2275 SendManyInner implements FutureListener
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
Labels: type/enhancement

#2278 Move from ChannelFutureListener to FutureListener
  reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
Labels: type/enhancement

#2279 Remove imports to multipart
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java
Labels: type/enhancement

#2282 HAProxyMessage is now a Resource
  reactor-netty-http/src/main/java/reactor/netty/http/server/HAProxyMessageReader.java
Labels: type/enhancement

#2284 Replace ByteBuf.release() with Buffer.close()
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpOperationsTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientOperationsTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
Labels: type/enhancement

#2285 Migrate Websocket to the new API
  reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketOutbound.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
Labels: type/enhancement

#2295 Update to netty-tcnative-boringssl-static v2.0.53.Final
  build.gradle
Labels: type/dependency-upgrade

#2288 Add new NettyOutbound#bufferAlloc
  reactor-netty-core/src/main/java/reactor/netty/NettyOutbound.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketOutbound.java
Labels: type/enhancement

#2289 Move read request from handlerAdded to channelRegistered
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
Labels: type/enhancement

#2290 Temporary exclude the check for the type of the executor
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
Labels: type/enhancement

#2298 Update to Netty v4.1.78.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/dependency-upgrade

#2301 Update to Netty 5.0.0.Alpha3-SNAPSHOT
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/BufferFlux.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSend.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
  reactor-netty-core/src/test/java/reactor/netty/channel/MonoSendManyTest.java
  reactor-netty-examples/build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/Http2ConnectionInfoTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpsSendFileTests.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
  reactor-netty-http/src/test/java/reactor/netty/transport/ByteBufAllocatorMetricsTest.java
Labels: type/enhancement

#2303 Tests need adaptation to work with Netty 5 changes and the new Buffer API
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH1Tests.java
Labels: type/enhancement

#2306 Replace usage ReferenceCountUtil.release(...) with Resource.dispose(...)
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2307 DefaultLastHttpContent is not DefaultHttpContent anymore but HttpContent
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2310 Ensure the next request is started once the previous is terminated
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2315 Switch to Micrometer 1.10.0-SNAPSHOT version
  build.gradle
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTimerObservationHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/dependency-upgrade

#2316 Variable can be replaced with pattern variable
  reactor-netty-core/src/main/java/reactor/netty/ChannelBindException.java
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/AddressUtils.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerEventLoopMeterRegistrar.java
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpOperations.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/read/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/uds/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/warmup/Application.java
  reactor-netty-http/src/main/java/reactor/netty/http/Http2SettingsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpServerRoutes.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/NonSslRedirectHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH2.java
Labels: type/enhancement

#2314 Add create method with metrics parameter in ConnectionProvider (#2313)
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
Labels: type/enhancement

#2317 Adapt to the new context propagation API
  build.gradle
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/observability/contextpropagation/propagator/ChannelContextContainerPropagator.java
  reactor-netty-core/src/main/java/reactor/netty/observability/contextpropagation/propagator/ReactorContextContainerPropagator.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/main/resources/META-INF/services/io.micrometer.contextpropagation.ContextContainerPropagator
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
Labels: type/enhancement

#2319 Updates to latest netty5 changes: userEventTriggered/half close/sync
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerEventLoopMeterRegistrar.java
  reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2318 reactor-netty-examples does not need dependency to the old ByteBuf API
  reactor-netty-examples/build.gradle
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/sse/Application.java
Labels: type/enhancement

#2320 AbstractHttpClientMetricsHandler/AbstractHttpServerMetricsHandler/AccessLogHandlerH1 works now only with Buffer
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
Labels: type/enhancement

#2321 Rename ByteBuf with Buffer
  README.md
  reactor-netty-core/src/main/java/reactor/netty/BufferFlux.java
  reactor-netty-core/src/test/java/reactor/netty/BufferFluxTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/logging/ReactorNettyLoggingHandlerTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/BufferFluxTest.java
  reactor-netty-http/src/test/java/reactor/netty/channel/FluxReceiveTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/UrlExceptionTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH1Tests.java
Labels: type/enhancement

#2322 Adapt the code to the changes in the ChannelHandler/ChannelHandlerContext methods names
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2323 DefaultHttp2DataFrame works with Send<Buffer>
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH2Tests.java
Labels: type/enhancement

#2311 Temporary build on CI Netty Contrib projects
  .github/workflows/check_transport.yml
  build.gradle
  gradle.properties
  reactor-netty-core/build.gradle
  reactor-netty-examples/build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
Labels: type/chore

#2237 Issue 2187
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/transport/AddressResolverGroupMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#2325 Adapt to the changed semantic for EmbeddedChannel
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
Labels: type/enhancement

#2326 Mark method param as Nullable
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
Labels: type/chore

#2328 Remove the temporary workarounds in CI build
  .github/workflows/check_transport.yml
  reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
Labels: type/chore

#2330 Enable tests for transferring files
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpsSendFileTests.java
Labels: type/enhancement

#2333 Ensure BufferMono is used when full request is needed
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
Labels: type/enhancement

#2334 [test] MessageToMessageEncoder now overrides encodeAndClose() instead of encode()
  reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java
Labels: type/enhancement

#2335 Ensure active connections is decremented
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
Labels: type/enhancement

#2338 Remove netty5 Unsafe class
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
Labels: type/enhancement

#2339 Use pattern matching for the instanceof
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSend.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
  reactor-netty-core/src/test/java/reactor/netty/resources/NewConnectionProviderTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2StreamBridgeClientHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/UriEndpoint.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH2.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/BaseAccessLogHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2342 Adapt to the changes in Netty 5 API
  .github/workflows/check_transport.yml
  reactor-netty-core/src/main/java/reactor/netty/NettyOutbound.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2StreamBridgeClientHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HAProxyMessageDetector.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/NonSslRedirectDetector.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
  reactor-netty-http/src/test/java/reactor/netty/transport/ByteBufAllocatorMetricsTest.java
Labels: type/enhancement

#2344 Adapt to the changed in AbstractChannel
  .github/workflows/check_transport.yml
  reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
Labels: type/enhancement

#2337 Re enable HttpMetricsHandlerTests in netty5 branch
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/enhancement
