Repository reactor/reactor-netty, pull requests merged in 2022-11, with the labels that each got.

#2327 Reintegrate multipart into netty5 branch
  build.gradle
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/server/multipart/Application.java
  reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/server/multipart/custom/Application.java
  reactor-netty5-http/build.gradle
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClient.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientFinalizer.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientForm.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientFormEncoder.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerFormDecoderProvider.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientTest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientWithTomcatTest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerFormDecoderProviderTests.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerPostFormTests.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
Labels: type/enhancement

#2562 Ensure junit tests do not have dependency to context-propagation
  reactor-netty-core/build.gradle
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/noMicrometerTest/java/reactor/netty/http/client/HttpClientNoMicrometerTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/chore

#2558 Add documentation and examples for the integration with Micrometer Tracing
  build.gradle
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/images/http-client-tracing.png
  docs/asciidoc/images/http-server-tracing.png
  docs/asciidoc/images/tcp-client-tracing.png
  docs/asciidoc/images/tcp-server-tracing.png
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  reactor-netty-examples/build.gradle
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/Application.java
  reactor-netty-http-brave/README.md
  reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/ReactorNettyHttpTracing.java
Labels: type/documentation

#2563 Remove from reactor-netty artifact the integration with Brave
  reactor-netty-http-brave/build.gradle
Labels: type/chore

#2564 Update Micrometer dependencies to 1.10.0-SNAPSHOT before GA
  build.gradle
Labels: type/chore

#2565 Use FutureMono instead of Mono#fromCompletionStage
  reactor-netty5-core/src/main/java/reactor/netty5/DisposableChannel.java
  reactor-netty5-core/src/main/java/reactor/netty5/FutureMono.java
  reactor-netty5-core/src/main/java/reactor/netty5/channel/ChannelOperations.java
  reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultLoopResources.java
  reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultPooledConnectionProvider.java
  reactor-netty5-core/src/main/java/reactor/netty5/udp/UdpOperations.java
  reactor-netty5-core/src/test/java/reactor/netty5/FutureMonoTest.java
  reactor-netty5-core/src/test/java/reactor/netty5/NettyOutboundTest.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/HttpOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/Http2Pool.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/client/WebsocketClientOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/WebsocketServerOperations.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientTest.java
  reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
Labels: type/enhancement

#2566 Fix javadoc
  reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java
Labels: type/documentation

#2568 Update Micrometer dependencies to 1.10.0
  build.gradle
Labels: type/enhancement

#2572 Update to Netty v4.1.85.Final
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2574 Bump Netty QUIC Codec to v0.0.34.Final
  build.gradle
Labels: type/enhancement

#2573 Update to Netty v5.0.0.Alpha6-SNAPSHOT
  .github/workflows/check_transport.yml
  build.gradle
Labels: type/enhancement

#2575 Bump netty-incubator-transport-native-io_uring to v0.0.16.Final
  build.gradle
Labels: type/enhancement

#2576 Reintegrate io_uring transport into netty5 branch
  build.gradle
  reactor-netty5-core/build.gradle
  reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultLoopIOUring.java
  reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultLoopNativeDetector.java
  reactor-netty5-http/build.gradle
  reactor-netty5/build.gradle
Labels: type/enhancement

#2577 Ensure Http2Pool can be stopped gracefully
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/bug

#2578 Ensure decoding failure is propagated
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2589 Update `Http2Pool` javadoc
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
Labels: type/documentation

#2592 Bump `Gradle` to version `7.6`
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type/dependency-upgrade

#2588 Support context propagation for ChannelHandler
  build.gradle
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  reactor-netty-core/build.gradle
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ChannelContextAccessorTest.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/TestThreadLocalAccessor.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/TestThreadLocalHolder.java
  reactor-netty-core/src/contextPropagationTest/resources/logback.xml
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/contextpropagation/ChannelContextAccessor.java
  reactor-netty-core/src/main/java/reactor/netty/contextpropagation/package-info.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/main/resources/META-INF/services/io.micrometer.context.ContextAccessor
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/custom/Application.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-http/src/contextPropagationTest/resources/logback.xml
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/enhancement

#2594 Support context propagation for `ChannelHandler`
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ChannelContextAccessorTest.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/TestThreadLocalAccessor.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/TestThreadLocalHolder.java
  reactor-netty-core/src/contextPropagationTest/resources/logback.xml
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/contextpropagation/ChannelContextAccessor.java
  reactor-netty-core/src/main/java/reactor/netty/contextpropagation/package-info.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/main/resources/META-INF/services/io.micrometer.context.ContextAccessor
  reactor-netty-http/build.gradle
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-http/src/contextPropagationTest/resources/logback.xml
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
Labels: type/enhancement
