Repository reactor/reactor-netty, pull requests merged in 2022-07, with the labels that each got.

#2346 Override the new ContextView#forEach
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
Labels: type/enhancement

#2351 Temporary build on CI with PR in sock-proxy
  .github/workflows/check_transport.yml
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
Labels: type/chore

#2352 With Java toolchain in place AllowRedefinitionToAddDeleteMethods is not needed
  build.gradle
  gradle/javadoc.gradle
  reactor-netty-core/build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-incubator-quic/build.gradle
Labels: type/enhancement

#2354 [doc ]Use Reactive Streams 1.0.3 version for javadoc generation
  build.gradle
Labels: type/documentation

#2355 [test] Fix warnings "unchecked method invocation"/"unchecked conversion"
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/chore

#2358 Adapt to changes made in Future interface
  .github/workflows/check_transport.yml
  reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java
  reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
  reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
  reactor-netty-core/src/test/java/reactor/netty/udp/UdpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/enhancement

#2359 Update Netty QUIC Codec to v0.0.28.Final
  build.gradle
Labels: type/dependency-upgrade

#2353 Make HttpMetricsHandlerTests stable
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/enhancement

#2360 [doc] Update Reactive Streams version in the reference documentation
  docs/asciidoc/getting-started.adoc
  docs/asciidoc/http-client-conn-provider.adoc
  docs/asciidoc/http-client.adoc
  docs/asciidoc/proxy.adoc
  docs/asciidoc/wire-logger.adoc
Labels: type/documentation

#2361 Use socks-proxy from main branch
  .github/workflows/check_transport.yml
Labels: type/enhancement

#2362 [doc] Fix the names of the metrics for ByteBufAllocator
  docs/asciidoc/alloc-metrics.adoc
Labels: type/documentation

#2364 Remove errorproneJavac specific for JDK 8
  gradle/errorprone.gradle
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/chore

#2366 Adapt to the changes in the context propagation API
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty/build.gradle
Labels: type/enhancement

#2365 Adapt to the changes for asynchronous connect in AbstractChannel
  .github/workflows/check_transport.yml
  reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
Labels: type/enhancement

#2367 Adapt to the new EventLoop API for checking the channel compatibility
  .github/workflows/check_transport.yml
  reactor-netty-core/src/main/java/reactor/netty/BufferFlux.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoop.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNIO.java
  reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java
Labels: type/enhancement

#2369 Update to Netty 5.0.0.Alpha3
  .github/workflows/check_transport.yml
  build.gradle
Labels: type/enhancement

#2371 Remove from CI the temporary workaround related to Netty Contrib projects
  .github/workflows/check_transport.yml
Labels: type/chore

#2376 Update Micrometer dependency to version 1.10.0-M3
  build.gradle
Labels: type/dependency-upgrade

#2378 [doc] Fix active memory metric name
  docs/asciidoc/faq.adoc
Labels: type/documentation

#2380 [doc] Javadoc link in reference documentation points to a concrete version
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  docs/asciidoc/udp-client.adoc
  docs/asciidoc/udp-server.adoc
Labels: type/documentation

#2381 [doc] Extract Netty javadoc link
  docs/asciidoc/http-server.adoc
Labels: type/documentation

#2382 [build] Fix the OSGi metadata for the imported optional packages
  reactor-netty5-core/build.gradle
  reactor-netty5-http/build.gradle
Labels: type/chore

#2385 Update Reference Documentation
  README.md
  docs/asciidoc/getting-started.adoc
  docs/asciidoc/http-client-conn-provider.adoc
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/proxy.adoc
  docs/asciidoc/tcp-client-conn-provider.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  docs/asciidoc/udp-client.adoc
  docs/asciidoc/udp-server.adoc
  docs/asciidoc/wire-logger.adoc
Labels: type/documentation

#2387 [doc] Remove the usage of the custom javadoc CSS
  docs/api/stylesheet.css
  gradle/javadoc.gradle
Labels: type/documentation

#2390 Update Netty Contrib projects version to 5.0.0.Alpha1
  .github/workflows/check_transport.yml
  .github/workflows/publish.yml
  build.gradle
Labels: type/enhancement

#2388 Use the new API Observation#parentObservation
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/internal/util/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ContextPropagationUtils.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/noMicrometerTest/java/reactor/netty/http/client/HttpClientNoMicrometerTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Labels: type/enhancement

#2394 Remove the dependency to the context propagation library
  reactor-netty-core/build.gradle
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/internal/util/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
Labels: type/enhancement

#2401 Adapt to the changed API for Micrometer's KeyName
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMeters.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProviderMeters.java
  reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMeters.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/EventLoopMeters.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
  reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerEventLoopMeterRegistrar.java
  reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttp2ConnectionProviderMeterRegistrar.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMeters.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java
Labels: type/enhancement

#2404 Bump MacOs image version to 11
  .github/workflows/check_netty_snapshots.yml
  .github/workflows/check_transport.yml
Labels: type/chore

#2399 Upgrade to Gradle v7.5
  codequality/checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/dependency-upgrade

#2408 Do not open a stream on a connection that received GOAWAY
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/bug

#2411 Use pattern for the field name when checking the classpath
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopIOUring.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNativeDetector.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HAProxyMessageReader.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
Labels: type/enhancement
