Repository reactor/reactor-netty, pull requests merged in 2023-04, with the labels that each got.

#2756 Ensure early dispose is delivered to late subscriber
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
  reactor-netty-core/src/test/java/reactor/netty/channel/FluxReceiveTest.java
Labels: type/bug

#2761 Parse X-Forwarded-Port header even if X-Forwarded-Host is not present
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/bug

#2763 Make it obvious that the test fails with `UnsupportedMessageTypeException`
  reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java
Labels: type/test

#2764 Use `Http2SslContextSpec` to build `SslContext` when `http2` enabled
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/echo/EchoServer.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/helloworld/HelloWorldServer.java
Labels: type/documentation

#2758 When in graceful shutdown, send `GO_AWAY` to notify the client to stop opening streams
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/bug

#2762 Depend on `Netty` `v4.1.91.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java
Labels: type/enhancement

#2765 ensures queue.clear is called in terminal cases for ASYNC fusion
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
  reactor-netty-core/src/test/java/reactor/netty/channel/MonoSendManyTest.java
Labels: type/enhancement

#2780 Bump `netty-tcnative-boringssl-static` to version `v2.0.60.Final`
  build.gradle
Labels: type/dependency-upgrade

#2783 Depend on `Netty` `v4.1.92.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
  reactor-netty-http/src/test/java/reactor/netty/http/server/Http2ConnectionInfoTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2773 Wrong host port 80 when only X-Forwarded-Proto: https is present
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/bug

#2787 Use `ConnectionInfo#getDefaultHostPort` when possible to remove code duplication
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/enhancement

#2790 Depend on `Netty QUIC Codec` `v0.0.40.Final`
  build.gradle
Labels: type/enhancement

#2777 Server might not send GOAWAY when some streams are being processed
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug
