Repository reactor/reactor-netty, pull requests merged in 2023-09, with the labels that each got.

#2883 Add a `http snoop server` sample
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/snoop/HttpSnoopClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/snoop/HttpSnoopServer.java
Labels: type/documentation

#2892 Fix flaky test
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/test

#2899 Add `GraalVM` smoke tests
  .github/workflows/check_graalvm.yml
  build.gradle
  gradle/javadoc.gradle
  gradle/setup.gradle
  reactor-netty-graalvm-smoke-tests/build.gradle
  reactor-netty-graalvm-smoke-tests/src/test/java/reactor/netty/http/HttpTests.java
  reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/jni-config.json
  reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/reflect-config.json
  reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/resource-config.json
  settings.gradle
Labels: type/test

#2864 Request for read interest when channel is unwritable while HttpClient.send(Mono) is used
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/TomcatServer.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java
Labels: type/bug

#2907 Bump `Gradle` to version `7.6.2`
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: type/dependency-upgrade

#2903 Fix HttpClientWithTomcatTest flaky test.
  reactor-netty-http/src/test/java/reactor/netty/TomcatServer.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java
Labels: type/test

#2902 Fix cross-site scripting vulnerability in test
  reactor-netty-http/src/test/java/reactor/netty/TomcatServer.java
Labels: type/test

#2911 Add nightly build with `Reactor Core` `3.6 SNAPSHOTs`
  .github/workflows/check_reactor_core_3.6_snapshots.yml
Labels: type/chore

#2912 Ensure `HttpClient#mapConnect() / #doOnRequestError()` are called when `HttpClient#headersWhen()` is used
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug
