Repository reactor/reactor-netty, pull requests merged in 2023-10, with the labels that each got.

#2916 Ensure `Expect` header is handled correctly with `HTTP/2`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH2.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
Labels: type/bug

#2919 Ensure connection closed when non `200` status for request with `Expect` header and incoming data not completed
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/bug

#2922 Add smoke test for `Reactor Core` feature `Hooks.enableAutomaticContextPropagation()`
  .github/workflows/check_reactor_core_3.6_snapshots.yml
  build.gradle
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Labels: type/test

#2924 Bump `Gradle` to version `7.6.3`
  gradle/wrapper/gradle-wrapper.properties
Labels: type/dependency-upgrade

#2925 Remove duplications
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Labels: type/test

#2926 More tests for `Reactor Core` feature `Hooks.enableAutomaticContextPropagation()`
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Labels: type/test

#2929 Bump `netty-tcnative-boringssl-static` to version `v2.0.62.Final`
  build.gradle
Labels: type/dependency-upgrade

#2932 Ensure metrics are unregistered when inactive connection pool is disposed
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/bug

#2937 Add root cause exception when throwing PrematureCloseException
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2939 Update TLS configuration defaults in javadoc
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
Labels: type/documentation

#2947 Bump `GraalVM` for `JDK 17 Community` to version `17.0.9`
  .github/workflows/check_graalvm.yml
Labels: type/dependency-upgrade

#2949 GraalVM smoke tests: Ensure the needed dependencies are built upfront
  .github/workflows/check_graalvm.yml
Labels: type/test

#2948 Add missing reflection configuration for `Netty 5`
  reactor-netty5-graalvm-smoke-tests/src/test/resources/META-INF/native-image/reflect-config.json
Labels: type/test

#2952 Update reference documentation for event loop group
  docs/asciidoc/eventloop.adoc
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  docs/asciidoc/udp-client.adoc
  docs/asciidoc/udp-server.adoc
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/eventloop/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/eventloop/Application.java
Labels: type/documentation
