Repository reactor/reactor-netty, pull requests merged in 2023-06, with the labels that each got.

#2820 Ensure any custom `CL`/`TE` header is removed when `304` response code
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java
Labels: type/bug

#2821 Add test for IllegalReferenceCountException/sendObject
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: for/netty, type/test

#2831 Depend on `Netty QUIC Codec` `v0.0.46.Final`
  build.gradle
Labels: type/enhancement

#2832 Add `HttpServer` `TLS Timeout Configuration` section to reference documentation
  docs/asciidoc/http-server.adoc
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/security/custom/Application.java
Labels: type/documentation

#2836 `HttpServer`: Add API for read related timeouts
  docs/asciidoc/http-server.adoc
  reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/read/timeout/Application.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/RequestTimeoutException.java
  reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2837 Depend on `Netty` `v4.1.94.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2840 Ensure handshake timeout is applied in case of SNI
  reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2841 Enhance context propagation reference documentation
  docs/asciidoc/http-client.adoc
  docs/asciidoc/http-server.adoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ChannelContextAccessorTest.java
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/custom/Application.java
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Labels: type/documentation

#2844 Fix memory leak of HTTP server on bind failure
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportConnectorTest.java
Labels: type/bug
