Repository reactor/reactor-netty, pull requests merged in 2023-01, with the labels that each got.

#2622 Support configurable DNS resolver cache
  docs/asciidoc/http-client.adoc
  docs/asciidoc/tcp-client.adoc
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
Labels: type/enhancement

#2627 Fix typos in comments of `HttpClientConnect`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
Labels: type/documentation

#2623 Ensure `CL`/`TE` headers are handled correctly for `204`/`205`/`304` status codes when server configured with `HTTP/2`
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2626 Update `ReactorNetty#IO_SELECT_COUNT` javadoc
  docs/asciidoc/tcp-client.adoc
  docs/asciidoc/tcp-server.adoc
  docs/asciidoc/udp-client.adoc
  docs/asciidoc/udp-server.adoc
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
Labels: type/documentation

#2632 Update `ReadMe` to have consistent formatting
  README.md
Labels: type/documentation

#2617 Add Reactor Netty version of Telnet example #761
  reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/telnet/TelnetClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/telnet/TelnetServer.java
Labels: type/documentation

#2633 Ensure `HttpServer` `Active Connections` metric is correct when connection closure before response write
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#2635 Use new `GitHub Actions` API for setting output
  gradle/setup.gradle
Labels: type/chore

#2646 Ensure `HttpServer` `minCompressionSize` is respected when `Content-Length` is not explicit and response is `Mono`
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
Labels: type/bug

#2647 Ensure response can disable `HttpServer` compression configuration
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
Labels: type/bug

#2650 Depend on `Netty` `v4.1.87.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2651 Bump `netty-tcnative-boringssl-static` to version `v2.0.56.Final`
  build.gradle
Labels: type/dependency-upgrade

#2636 Add Reactor Netty version of the Quote of the Moment example #761
  reactor-netty-examples/src/main/java/reactor/netty/examples/udp/qotm/QuoteOfTheMomentClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/udp/qotm/QuoteOfTheMomentServer.java
Labels: type/documentation

#2655 Allow to configure colocation when creating LoopResources
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopResources.java
  reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java
Labels: type/enhancement

#2661 Remove `JAPICMP` exclusions that are relevant for the previous releases
  reactor-netty-core/build.gradle
Labels: type/chore

#2660 Ensure `IdleTimeoutHandler` receives always `channelRead` events
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/IdleTimeoutHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/bug

#2665 Polish `LogTracker`
  reactor-netty-core/src/testFixtures/java/reactor/netty/LogTracker.java
Labels: type/chore

#2666 Replace `AccessLogAppender` with `LogTracker`
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/test

#2668 Extend `HttpClient`/`HttpServer` combinations used for `HttpMetricsHandlerTests`
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/test

#2659 Allow H1, H2, and H2C protocol for HttpClient
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
Labels: type/bug

#2673 Fix `NullPointerException` when `followRedirect` is true, but there is no `location` header
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/RedirectClientException.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
Labels: type/bug

#2676 Reduce code duplication
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
Labels: type/chore

#2679 `Reactor Netty` javadoc generation does not need `jackson-databind` javadoc url
  build.gradle
Labels: type/documentation

#2680 Use empty shared `ChannelHandler` for inbound stream handling on the `HttpClient`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
Labels: type/enhancement
