Repository reactor/reactor-netty, pull requests merged in 2023-05, with the labels that each got.

#2789 Default forwarded header handler should only using ConnectionInfo public API
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/Http2ConnectionInfoTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/forwardheaderhandler/CustomXForwardedHeadersHandler.java
Labels: type/bug

#2755 Avoid null metric recorder remoteAddress parameters
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2795 Adapt Http2SettingsSpecTests to new netty error messages
  reactor-netty-http/src/test/java/reactor/netty/http/Http2SettingsSpecTests.java
Labels: type/test

#2792 responseContent() remove excess ByteBufFlux conversion
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFinalizer.java
Labels: type/enhancement

#2799 Bump `netty-tcnative-boringssl-static` to version `v2.0.61.Final`
  build.gradle
Labels: type/dependency-upgrade

#2808 Depend on `Netty QUIC Codec` `v0.0.41.Final`
  build.gradle
Labels: type/enhancement

#2812 Depend on `Netty` `v4.1.93.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2813 Depend on `Netty QUIC Codec` `v0.0.42.Final`
  build.gradle
Labels: type/enhancement

#2814 Depend on `Netty QUIC Codec` `v0.0.43.Final`
  build.gradle
Labels: type/enhancement

#2815 Add `Brotli` compression test
  build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
Labels: type/test
