Repository reactor/reactor-netty, pull requests merged in 2023-03, with the labels that each got.

#2712 Handling `X-Forwarded-Host` with value `host:port`
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/enhancement

#2714 Add `ConnectionInformation#hostName/hostPort`
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInformation.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/enhancement

#2715 When the scheme is `https`/`wss`, the https default port is used as a fallback option
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
Labels: type/enhancement

#2720 Fix test failure on Windows OS
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/chore

#2721 Fix flaky test
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/chore

#2722 Depend on `Netty QUIC Codec` `v0.0.38.Final`
  build.gradle
Labels: type/enhancement

#2724 Handle empty `HOST` header when processing connection information
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Labels: type/bug

#2727 Depend on `Netty` `v4.1.90.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2732 Replace Objects.hash()
  reactor-netty-core/src/main/java/reactor/netty/channel/MeterKey.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/Http2SettingsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java
Labels: type/enhancement

#2736 When graceful shutdown, ensure the streams are processed before closing connection
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#2737 Replace `Objects.hash()`
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicInitialSettingsSpec.java
Labels: type/enhancement

#2739 Ensure correct initial capacity is used for the map
  reactor-netty-core/src/main/java/reactor/netty/internal/util/MapUtils.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServerBind.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpPredicate.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java
Labels: type/bug

#2742 Add `DEBUG` log for `ServerTransport#disposeNow`
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
Labels: type/enhancement

#2733 Smarter usage of `FQDN` in `PoolKey`
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/test/java/reactor/netty/resources/PoolKeyTest.java
Labels: type/enhancement

#2745 Support a custom `DnsAddressResolverGroup` builder function
  docs/asciidoc/http-client.adoc
  docs/asciidoc/tcp-client.adoc
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
Labels: type/enhancement

#2747 Add API for configuring custom `ObservationRegistry`
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
Labels: type/enhancement

#2757 Depend on `Netty QUIC Codec` `v0.0.39.Final`
  build.gradle
Labels: type/enhancement
