Repository reactor/reactor-netty, pull requests merged in 2023-02, with the labels that each got.

#2682 Depend on `Netty QUIC Codec` `v0.0.36.Final`
  build.gradle
Labels: type/enhancement

#2685 Bump `netty-tcnative-boringssl-static` to version `v2.0.57.Final`
  build.gradle
Labels: type/dependency-upgrade

#2677 Add Reactor Netty version of secure chat server example reactor#761
  reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/securechat/SecureChatClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/securechat/SecureChatServer.java
Labels: type/documentation

#2686 When constructing `HttpServerOperations` specify `HTTP/1.1` or `HTTP/2`
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#2688 Fix `Netty 5` leak detection property name
  build.gradle
Labels: type/chore

#2694 Depend on `Netty` `v4.1.89.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#2699 Bump `netty-tcnative-boringssl-static` to version `v2.0.59.Final`
  build.gradle
Labels: type/dependency-upgrade

#2707 Bump `Gradle` to version `7.6.1`
  gradle/wrapper/gradle-wrapper.properties
Labels: type/dependency-upgrade
