Repository reactor/reactor-netty, pull requests merged in 2024-04, with the labels that each got.

#3126 validate zstd compression
  build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
Labels: type/test

#3128 Remove unnecessary resources
  docs/modules/ROOT/assets/images/RBP.png
  docs/modules/ROOT/assets/images/RBWP.png
  docs/modules/ROOT/assets/images/broadcast.png
  docs/modules/ROOT/assets/images/bus-overview.png
  docs/modules/ROOT/assets/images/core-overview.png
  docs/modules/ROOT/assets/images/longMaxThreading.png
  docs/modules/ROOT/assets/images/marble/marble-101.png
  docs/modules/ROOT/assets/images/marble/marble-overflowbuffer.png
  docs/modules/ROOT/assets/images/marble/marble-overflowdrop.png
  docs/modules/ROOT/assets/images/marble/marble-requestwhen.png
  docs/modules/ROOT/assets/images/marble/marble-throttle.png
  docs/modules/ROOT/assets/images/modules.png
  docs/modules/ROOT/assets/images/nThreading.png
  docs/modules/ROOT/assets/images/overview.png
  docs/modules/ROOT/assets/images/rbd2.png
  docs/modules/ROOT/assets/images/rs.png
  docs/modules/ROOT/assets/images/signals.png
  docs/modules/ROOT/assets/images/streams-overview.png
  docs/modules/ROOT/assets/images/wiringup.png
Labels: type/documentation

#3129 Fix links to `Connection Timeout` and `Timeout Configuration`
  docs/modules/ROOT/pages/faq.adoc
  docs/modules/ROOT/pages/http-client.adoc
Labels: type/documentation

#3130 Keep the `indent` 0
  docs/modules/ROOT/pages/tcp-server.adoc
Labels: type/documentation

#3131 Move `Wire Logger Formatters` to the correct level in the navigation
  docs/modules/ROOT/partials/wire-logger.adoc
Labels: type/documentation

#3133 Add links to the examples
  docs/antora.yml
  docs/modules/ROOT/pages/http-client.adoc
  docs/modules/ROOT/pages/http-server.adoc
  docs/modules/ROOT/pages/tcp-client.adoc
  docs/modules/ROOT/pages/tcp-server.adoc
  docs/modules/ROOT/pages/udp-client.adoc
  docs/modules/ROOT/pages/udp-server.adoc
  docs/modules/ROOT/partials/eventloop.adoc
  docs/modules/ROOT/partials/http-client-conn-provider.adoc
  docs/modules/ROOT/partials/proxy.adoc
  docs/modules/ROOT/partials/tcp-client-conn-provider.adoc
  docs/modules/ROOT/partials/wire-logger.adoc
Labels: type/documentation

#3135 Attach description to the URLs
  docs/modules/ROOT/pages/http-client.adoc
  docs/modules/ROOT/pages/http-server.adoc
  docs/modules/ROOT/pages/tcp-client.adoc
  docs/modules/ROOT/pages/tcp-server.adoc
  docs/modules/ROOT/pages/udp-client.adoc
  docs/modules/ROOT/pages/udp-server.adoc
  docs/modules/ROOT/partials/alloc-metrics.adoc
  docs/modules/ROOT/partials/conn-provider-metrics.adoc
  docs/modules/ROOT/partials/eventloop-metrics.adoc
  docs/modules/ROOT/partials/http-client-conn-provider.adoc
Labels: type/documentation

#3136 Fix copyright year
  gradle/antora-docs.gradle
Labels: type/chore

#3137 Remove wrong description in docsZip
  reactor-netty/build.gradle
Labels: type/chore

#3140 Pdf is not included in milestone release
  reactor-netty/build.gradle
Labels: type/chore

#3141 Remove unnecessary manipulation of SUPPORT.adoc as it is a partial content
  docs/modules/ROOT/pages/getting-started.adoc
  gradle/antora-docs.gradle
Labels: type/documentation

#3143 Bump `errorprone` to version `3.1.0`
  build.gradle
  gradle/errorprone.gradle
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
Labels: type/dependency-upgrade

#3144 Depend on `Brave` `v6.0.2`
  build.gradle
  reactor-netty-examples/build.gradle
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/custom/Application.java
Labels: type/enhancement

#3145 Bump `Gradle` to version `8.7`
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type/chore

#3146 Bump `com.github.johnrengelman.shadow` to version `8.1.1`
  .github/dependabot.yml
  build.gradle
  reactor-netty-core/build.gradle
Labels: type/dependency-upgrade

#3148 Update Algolia environment variables
  gradle/antora-docs.gradle
Labels: type/chore

#3151 Remove unnecessary attribute in proxy.adoc
  docs/modules/ROOT/partials/proxy.adoc
Labels: type/chore

#3156 Replace gradle/wrapper-validation-action with gradle/actions/wrapper-validation
  .github/workflows/check_transport.yml
Labels: type/chore

#3150 Make `ProtocolSslContextSpec` generic
  build.gradle
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SslContextSpec.java
Labels: type/enhancement

#3152 Add `HTTP/3` initial settings
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http3SettingsSpecTest.java
Labels: type/enhancement

#3159 Depend on `Netty` `v4.1.109.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3138 Re enable full build with jdk17
  build.gradle
  gradle/setup.gradle
  reactor-netty/build.gradle
Labels: type/chore

#3161 Add `HttpProtocol#HTTP3`
  reactor-netty-http/src/main/java/reactor/netty/http/HttpProtocol.java
  reactor-netty-http/src/main/java/reactor/netty/http/internal/Http3.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/enhancement

#3158 Limit permission in publish cleanup job
  .github/workflows/publish.yml
Labels: type/chore

#3160 Deprecate `SslContextSpec#sslContext(reactor.netty.tcp.SslProvider.ProtocolSslContextSpec)`
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
Labels: type/enhancement, warn/deprecation

#3162 Build Antora only when publishing
  docs/build.gradle
  reactor-netty/build.gradle
Labels: type/chore

#3165 Remove useless check
  build.gradle
  reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java
Labels: type/test

#3166 Bump `zipkin-sender-urlconnection` to version `2.17.2`
  build.gradle
Labels: type/dependency-upgrade

#3164 Depend on `Micrometer` `v1.13.0-SNAPSHOT`
  build.gradle
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/custom/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/custom/Application.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Labels: type/enhancement

#3177 Remove unnecessary `:toc:` from `appendices.adoc`
  docs/modules/ROOT/pages/appendices.adoc
Labels: type/chore

#3183 Annotate `HTTP/3` server support as incubating
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SslContextSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpProtocol.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/enhancement

#3186 Add `wiretap` for `HTTP/3` frames
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ChannelInitializer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
Labels: type/enhancement

#3192 Add `compression` for `HTTP/3` server support
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/enhancement

#3193 Add `metrics` for `HTTP/3` server support
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
Labels: type/enhancement

#3196 Suppress deprecation warning
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerPostFormTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
  reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java
Labels: type/test

#3197 Add dependency to `Netty HTTP3 Codec` for aggregated javadoc
  build.gradle
  reactor-netty/build.gradle
Labels: type/documentation

#3201 Remove the workaround for Micrometer - Mockito issue
  reactor-netty-http/build.gradle
Labels: type/test

#3210 Always use remote socket address for the metrics
  reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#3212 Update to `macos-12` runner image
  .github/workflows/check_netty_snapshots.yml
  .github/workflows/check_transport.yml
Labels: type/chore

#3211 Cache the request info when collecting metrics
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/enhancement

#3214 Fix Authors attribute
  docs/antora.yml
Labels: type/documentation

#3215 Reuse reactor-netty-github-repo-attribute when possible
  docs/modules/ROOT/pages/about-doc.adoc
Labels: type/documentation

#3216 Remove unused reactor.css
  docs/antora-playbook.yml
  docs/modules/ROOT/pages/stylesheets/reactor.css
Labels: type/documentation
