Repository reactor/reactor-netty, pull requests merged in 2024-10, with the labels that each got.

#3436 Parse X-Forwarded-Prefix request header
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRequest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/forwardheaderhandler/CustomXForwardedHeadersHandler.java
Labels: type/enhancement

#3451 Depend on `Netty` `v4.1.114.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3453 Support `allowPartialChunks` in the `HttpDecoderSpec`
  reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpDecoderSpecTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#3457 Switch from `macOS-12` to `macOS-13` runner image
  .github/workflows/check_graalvm.yml
  .github/workflows/check_netty_snapshots.yml
  .github/workflows/check_transport.yml
Labels: type/chore

#3459 When terminating detach the connection from request/response objects
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
  reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingHttpServerDecorator.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug

#3471 Fix typo in javadoc for `allowPartialChunks` setting
  reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
Labels: type/documentation

#3480 Temporary download manually `GraalVM` distribution
  .github/workflows/check_graalvm.yml
Labels: type/chore

#3481 Ensure body is sent when `DELETE` and `Transfer-Encoding`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug

#3483 Revert "[build] Temporary download manually GraalVM distribution (#34…
  .github/workflows/check_graalvm.yml
Labels: type/chore

#3484 Delay sending the server preface when `SNI` is configured
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#3487 Ensure `HttpInfos#version` returns the correct protocol
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
Labels: type/bug
