Repository reactor/reactor-netty, pull requests merged in 2024-06, with the labels that each got.

#3280 Adapt access log to the delayed last flush operation
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AbstractAccessLogArgProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH1.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java
Labels: type/enhancement

#3281 Extend the documentation for the shared (default) `ConnectionProvider` and `Event Loop Group`
  docs/asciidoc/eventloop.adoc
  docs/asciidoc/http-client-conn-provider.adoc
  docs/asciidoc/tcp-client-conn-provider.adoc
Labels: type/documentation

#3282 Adapt metrics to the delayed last flush operation
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java
Labels: type/enhancement

#3286 Enhance robustness of publish.yml related to Antora
  .github/workflows/publish.yml
Labels: type/documentation

#3287 Enhance Antora gradle build
  gradle/antora-docs.gradle
  reactor-netty/build.gradle
Labels: type/documentation

#3276 Make `MonoSend.MAX_SIZE` configurable by system property
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSend.java
Labels: type/enhancement

#3293 Depend on `Netty` `v4.1.111.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3294 Depend on `Netty QUIC Codec` `v0.0.64.Final`
  build.gradle
Labels: type/enhancement

#3290 Close the connection when decoding exception happens
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug

#3298 Test `TooLongFrameException` is propagated and connection closed
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
Labels: type/test

#3300 `Http2Pool`: when applying `acquireTimeout`, check for current pending `Borrowers`
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
Labels: type/bug

#3311 Add `HTTP/3` client initial settings
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/http3/Application.java
  reactor-netty-http/build.gradle
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3SettingsSpecTest.java
  reactor-netty-http/src/http3Test/resources/logback.xml
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ChannelInitializer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/enhancement

#3312 Add `HttpProtocol#HTTP3`
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSecure.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java
Labels: type/enhancement

#3314 Add bind support for `DefaultPooledConnectionProvider`
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
Labels: type/enhancement

#3317 Add `Http3Pool`
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Pool.java
Labels: type/enhancement

#3319 Initial `HTTP/3` client support
  docs/modules/ROOT/pages/http-client.adoc
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/http3/Application.java
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ChannelInitializer.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3StreamBridgeClientHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java
  reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpConnectionProviderTest.java
Labels: type/enhancement

#3320 Depend on `Netty QUIC Codec` `v0.0.65.Final`
  build.gradle
Labels: type/enhancement

#3321 When an explicit `EventLoopGroup` is configured ensure only one connection pool is created
  reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
  reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
Labels: type/bug

#3309 Modernize Antora Build
  .gitignore
  build.gradle
  docs/package.json
  gradle/antora-docs.gradle
Labels: type/documentation
