Repository reactor/reactor-netty, pull requests merged in 2024-07, with the labels that each got.

#3331 Add `Brotli` support for `HttpClient`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/enhancement

#3345 Publish javadoc / reference docs to spring.io
  .github/workflows/publish.yml
  build.gradle
  buildSrc/src/main/groovy/reactor/netty/docs/gradle/DeployDocs.groovy
  reactor-netty/build.gradle
Labels: type/documentation

#3349 Polish Javadoc for HttpClient.compress()
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
Labels: type/documentation

#3352 Do not record an exception when the request information is not available
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
Labels: type/bug

#3354 Cache the infomation whether the request is websocket
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
Labels: type/enhancement

#3355 Cache `Content-Length` when it is about to send the `FullHttpResponse`
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
Labels: type/enhancement

#3356 Use `doFinally` in order to handle `cancel` and `error` signals
  reactor-netty-http/build.gradle
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
Labels: type/enhancement

#3359 Resolve on demand the path from the request uri
  reactor-netty-http/src/main/java/reactor/netty/http/HttpInfos.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement, warn/behavior-change

#3361 Depend on `Netty` `v4.1.112.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3369 Always `decode` in an event loop
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
Labels: type/bug

#3370 `HttpDecoderSpec#validateHeaders()` specifies whether request/response headers are validated
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#3375 Simplify `HttpServerOperations#onInboundNext`
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
Labels: type/enhancement

#3376 Simplify `HttpTrafficHandler#write`
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
Labels: type/enhancement
