Repository reactor/reactor-netty, pull requests merged in 2024-01, with the labels that each got.

#3013 Clarify TCP fallback is enabled by default for Host Name Resolution.
  docs/asciidoc/http-client.adoc
  docs/asciidoc/tcp-client.adoc
Labels: type/documentation

#3020 Update `dependabot` configuration
  .github/dependabot.yml
Labels: type/chore

#3030 Depend on `Netty` `v4.1.105.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3031 Ensure `ChannelHandlerContext.isRemoved` is called only when in event loop
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
Labels: type/bug

#3032 Obtain `Http2FrameCodec` context only when needed
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
Labels: type/enhancement

#3034 Depend on `Netty` `v4.1.106.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3037 Ensure `websocket` `compression` is enabled when `server` is configured with `HttpProtocol.H2C` and `HttpProtocol.HTTP1.1`
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
Labels: type/bug

#3038 Bump `metadata repository` to version `0.3.6`
  reactor-netty-graalvm-smoke-tests/build.gradle
  reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/jni-config.json
  reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/reflect-config.json
  reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/resource-config.json
Labels: type/dependency-upgrade

#3039 Ensure cookies can be added by `BiConsumer` provided with `HttpClient#followRedirect`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
Labels: type/bug, warn/regression

#3046 Update `CodeQL` with the latest configurations
  .github/workflows/codeql-analysis.yml
Labels: type/chore

#3047 Depend on `Netty QUIC Codec` `v0.0.56.Final`
  build.gradle
Labels: type/enhancement

#3048 Pin `GitHub Actions` versions
  .github/workflows/check_netty_snapshots.yml
  .github/workflows/check_transport.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish.yml
Labels: type/chore
