Repository reactor/reactor-netty, pull requests merged in 2024-12, with the labels that each got.

#3530 Handle the incoming `LastHttpContent` with no content as if it is `EMPTY_LAST_CONTENT`
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
Labels: type/enhancement

#3526 Ensure `HttpClient` sends full request when the send function does not change `NettyOutbound`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java
Labels: type/bug

#3536 `HTTP/3`: Ensure `HttpClient` sends full request when the send function does not change `NettyOutbound`
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ConnectionProvider.java
Labels: type/bug

#3537 Enable `HTTP/3` metrics test
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
Labels: type/test

#3542 Fix ClassCastException in `HttpOperations#initShortId()`
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
Labels: type/bug

#3543 Ensure the request counter is updated once when the request is received
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#3540 HttpServerRequest::receiveContent() never emits any value nor completes when HTTP/1.1 TLS Upgrade (RFC-2817) kicks in
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug

#3549 Do not add `Transfer-Encoding` for `DELETE` with no body
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug, warn/regression

#3550 Depend on `Netty` `v4.1.116.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3574 Bump `Gradle` to version `8.12`
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: type/chore

#3575 `CancelReceiverHandlerTest`: Move the check for `ByteBuf.release` to `channelReadComplete`
  reactor-netty-core/src/testFixtures/java/reactor/netty/CancelReceiverHandlerTest.java
Labels: type/test
