Repository reactor/reactor-netty, pull requests merged in 2024-05, with the labels that each got.

#3229 Ensure `HttpServerMetricsRecorder#recordServerConnectionInactive/Close` is invoked for websockets
  reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug

#3230 Always add `proxy.address` tag for the client metrics
  reactor-netty-core/src/main/java/reactor/netty/Metrics.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpSecureMetricsTests.java
  reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
Labels: type/bug, warn/regression

#3231 Obtain the channel from `ChannelHandlerContext` instead of `HttpServerOperations`
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/enhancement

#3235 Ensure `ConnectionProvider` metrics are disposed unconditionally when graceful shutdown
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
Labels: type/bug

#3236 Ensure `ByteBuf#release` is invoked for already sent `HTTP/2` response
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/bug

#3239 Make pending responses log messages consistent
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
Labels: type/enhancement

#3238 Always use block/blockLast/verify with timeout
  reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
  reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java
  reactor-netty-core/src/test/java/reactor/netty/channel/MonoSendManyTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpResourcesTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportResolverHooksTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportConnectorTest.java
  reactor-netty-core/src/test/java/reactor/netty/udp/UdpResourcesTest.java
  reactor-netty-http/src/noMicrometerTest/java/reactor/netty/http/client/HttpClientNoMicrometerTest.java
  reactor-netty-http/src/test/java/reactor/netty/channel/ChannelOperationsHandlerTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpErrorTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpResourcesTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
  reactor-netty-incubator-quic/src/test/java/reactor/netty/incubator/quic/QuicServerTests.java
Labels: type/test

#3241 Depend on `Micrometer` `v1.13.0`
  build.gradle
Labels: type/enhancement

#3243 Allow using SocketAddress proxies instead of just InetSocketAddress
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ProxyProviderTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
Labels: type/enhancement

#3246 When `HttpOperations#afterMarkSentHeaders` throws an error in `HttpOperations#sendObject`, ensure the `ByteBuf` is released just once
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
Labels: type/bug

#3259 Depend on `Netty` `v4.1.110.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3264 Depend on `Netty QUIC Codec` `v0.0.63.Final`
  build.gradle
  reactor-netty-incubator-quic/src/test/java/reactor/netty/incubator/quic/QuicClientTests.java
  reactor-netty-incubator-quic/src/test/java/reactor/netty/incubator/quic/QuicServerTests.java
Labels: type/enhancement

#3252 Fix `HTTP/2` pool `recordPendingSuccess/FailureAndLatency` not recorded without timeout
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
Labels: type/bug

#3250 Immediately mark outbound as complete when sending `Mono` or `Object`
  reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java
Labels: type/enhancement

#3271 Add possibility to delay the last flush operation
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java
Labels: type/enhancement
