Repository reactor/reactor-netty, pull requests merged in 2025-04, with the labels that each got.

#3703 Depend on `Netty QUIC Codec` `v0.0.71.Final`
  build.gradle
Labels: type/enhancement

#3709 Annotate with `Nullable`, `FastThreadLocal` that can become null
  reactor-netty-core/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java
Labels: type/enhancement

#3712 Enable set up `TcpResources` default max connection by setting
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
Labels: type/enhancement

#3713 Bump `Gradle` to version `8.13`
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: type/chore

#3715 Support `HttpServerRoutes#ws` with `HTTP/2`
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2WebsocketServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRoutes.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2WebsocketTest.java
Labels: type/enhancement

#3719 Bump `metadata repository` to version `0.3.19`
  reactor-netty-graalvm-smoke-tests/build.gradle
Labels: type/dependency-upgrade

#3725 Ensure `reactor.netty.http.server.connections.active` is updated when there is no `HttpServerOperations`
  reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
Labels: type/bug

#3737 Depend on `Netty QUIC Codec` `v0.0.72.Final`
  build.gradle
Labels: type/enhancement

#3735 Add request and response header iterators to `AccessLogArgProvider`
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH1.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH2.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH3.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderH1Tests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderH2Tests.java
Labels: type/enhancement

#3700 Support error log handler for Http server
  docs/modules/ROOT/pages/http-server.adoc
  reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
  reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/CustomFormatAndFilterErrorLogApplication.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/CustomLogErrorFormatApplication.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/FilterLogErrorApplication.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/AbstractErrorLogArgProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/BaseErrorLogHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLog.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLogArgProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLogHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLoggingEvent.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLog.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLogArgProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLogFactory.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLoggingEvent.java
  reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
  reactor-netty-http/src/test/java/reactor/netty/http/server/logging/error/ErrorLogTest.java
Labels: type/enhancement

#3743 Ensure the default compression configuration is taken from Netty
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/DeflateOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/GzipOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/ZstdOption.java
Labels: type/bug

#3744 Ensure the exception is propagated in case of delayed address resolution
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug
