Repository reactor/reactor-netty, pull requests merged in 2025-07, with the labels that each got.

#3823 Improve protocol validation in `Forwarded`/`X-Forwarded-Proto` header parsing
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
Labels: type/enhancement

#3830 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type/chore

#3829 Update support listing reference
  docs/modules/ROOT/pages/getting-started.adoc
Labels: type/chore

#3832 Add proper initialisation of `maxConcurrentStreams` when successful `HTTP/1.1` to `HTTP/2` upgrade
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
Labels: type/bug

#3838 Ensure the `HTTP/2` upgrade stream inherits the proper state from the original `HTTP/1.1` connection when successful upgrade from `HTTP/1.1` to `HTTP/2`
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
Labels: type/bug

#3840 Depend on `Micrometer` `1.16.0-M1`
  build.gradle
Labels: type/enhancement

#3841 Depend on `Netty` `v4.2.3.Final`
  .github/workflows/check_netty_4_1_snapshots.yml
  .github/workflows/check_netty_4_2_snapshots.yml
  build.gradle
Labels: type/enhancement

#3844 Depend on `Netty` `v4.1.123.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3851 `Reactor Netty` `HTTP/3` is no more in incubator
  build.gradle
  docs/modules/ROOT/pages/http-client.adoc
  docs/modules/ROOT/pages/http-server.adoc
  reactor-netty-examples/build.gradle
  reactor-netty-http/build.gradle
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3SettingsSpecTest.java
  reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
  reactor-netty-http/src/http3Test/java/reactor/netty/http/server/logging/AccessLogArgProviderH3Tests.java
  reactor-netty-http/src/http3Test/java/reactor/netty/http/server/logging/error/ErrorLogTest.java
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/Http3SslContextSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpProtocol.java
  reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ChannelInitializer.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Pool.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3StreamBridgeClientHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/internal/Http3.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ChannelInitializer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH3.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerFactory.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH3.java
  reactor-netty/build.gradle
Labels: type/enhancement
