Repository reactor/reactor-netty, pull requests merged in 2025-02, with the labels that each got.

#3619 Bump `com.gradleup.shadow` to version `8.3.6`
  build.gradle
  reactor-netty-core/build.gradle
Labels: type/dependency-upgrade

#3622 Bump `netty-tcnative-boringssl-static` to version `v2.0.70.Final`
  build.gradle
Labels: type/dependency-upgrade

#3623 Depend on `Netty` `v4.1.118.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3626 Add `Nullable` annotation to overridden method
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
  reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/FailedHttpClientRequest.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpServerRoutes.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Labels: type/bug

#3628 Remove `Nullable` annotation from method parameter
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
Labels: type/bug

#3629 Add missing `Nullable` annotation
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
Labels: type/bug

#3639 Fix `NullPointerException` in `Http2SettingsSpec#hashCode`
  reactor-netty-http/src/main/java/reactor/netty/http/Http2SettingsSpec.java
Labels: type/bug

#3640 Annotate with `Nullable`, fields that can become null
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClient.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConfig.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConnect.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicOperations.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicResources.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServer.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServerBind.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServerConfig.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicTransportConfig.java
  reactor-netty-incubator-quic/src/test/java/reactor/netty/incubator/quic/BaseQuicTests.java
Labels: type/enhancement

#3642 Annotate with `Nullable`, fields that can become null
  reactor-netty-graalvm-smoke-tests/src/test/java/reactor/netty/http/HttpTests.java
Labels: type/enhancement

#3645 Annotate with `Nullable`, fields that can become null
  reactor-netty-core/src/main/java/reactor/netty/DisposableChannel.java
  reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
  reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MeterKey.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
  reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
  reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServerConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
  reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpResources.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpServer.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerBind.java
  reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerConfig.java
  reactor-netty-core/src/test/java/reactor/netty/ChannelOperationsIdTest.java
  reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
  reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
  reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/BlockingConnectionTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpResourcesTest.java
  reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
  reactor-netty-core/src/test/java/reactor/netty/transport/AddressUtilsTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ProxyProviderTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/ServerTransportTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportConnectorTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/TransportTest.java
  reactor-netty-core/src/test/java/reactor/netty/transport/logging/AdvancedByteBufFormatTest.java
  reactor-netty-core/src/test/java/reactor/netty/udp/UdpMetricsTests.java
  reactor-netty-core/src/test/java/reactor/netty/udp/UdpResourcesTest.java
Labels: type/enhancement

#3646 Add missing `Nullable` annotation
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRequest.java
Labels: type/bug

#3647 Make `Subscription` non nullable and suppress `NullAway`
  reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ConnectionProvider.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConnect.java
  reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServerBind.java
Labels: type/enhancement

#3632 Add `Http2MeterRegistrarAdapter` to track active and pending streams in HTTP/2
  docs/modules/ROOT/partials/http-client-conn-provider.adoc
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/pool/metrics/http/Application.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/pool/metrics/http2/Application.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ConnectionProvider.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionPoolMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpDelegatingConnectionPoolMetrics.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpMeterRegistrarAdapter.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PooledConnectionProviderCustomMetricsTest.java
Labels: type/enhancement

#3656 Publish milestones and release candidates to `Maven Central`
  .github/workflows/publish.yml
  README.md
  build.gradle
  docs/modules/ROOT/pages/getting-started.adoc
Labels: type/chore

#3657 Fix reference documentation links to point to the correct branch
  docs/antora.yml
  docs/modules/ROOT/pages/about-doc.adoc
Labels: type/chore

#3659 Depend on `Netty` `v4.1.119.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement
