Repository reactor/reactor-netty, pull requests merged in 2025-01, with the labels that each got.

#3571 Remove unnecessary conditional statements in log
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
Labels: type/bug

#3554 Add Reactor Netty version of `CORS` HTTP server example
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/cors/HttpCorsServer.java
Labels: type/documentation

#3578 Add `HTTP2`/`HTTP3` configuration to the `HTTP` examples
  reactor-netty-examples/build.gradle
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/cors/HttpCorsServer.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/echo/EchoClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/echo/EchoServer.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/helloworld/HelloWorldClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/helloworld/HelloWorldServer.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/snoop/HttpSnoopClient.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/http/snoop/HttpSnoopServer.java
Labels: type/documentation

#3581 Ensure `DisposedChannelConfig#setAutoRead` does not change auto-read configuration
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
Labels: type/bug, warn/regression

#3582 `Http2Pool`: Do not proceed with the acquisition if `Borrower` is cancelled
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
Labels: type/enhancement

#3566 Configuration for setting maximum number of connection pools to be created
  reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
  reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/enhancement

#3589 Depend on `Netty` `v4.1.117.Final`
  .github/workflows/check_netty_snapshots.yml
  build.gradle
Labels: type/enhancement

#3592 Make `ChannelOperations.DisposedChannel#close` non operational
  reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
Labels: type/bug, warn/regression

#3596 When `Mono#empty` is provided as a deferred configuration, continue with the actual configuration
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Labels: type/bug

#3598 Use `DnsNameResolverBuilder#datagramChannelFactory` instead of the deprecated `DnsNameResolverBuilder#channelFactory`
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
Labels: type/enhancement

#3599 Remove `1.0.x` branch from `GitHub` workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish.yml
Labels: type/chore

#3600 Explicitly specify java version for `CodeQL`
  .github/workflows/codeql-analysis.yml
Labels: type/chore

#3593 Support for dynamic proxy configuration at the HTTP protocol level
  docs/modules/ROOT/partials/proxy.adoc
  reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
  reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/proxy/deferred/Application.java
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java
Labels: type/enhancement

#3602 When null is provided as a deferred configuration, continue with the current configuration
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
Labels: type/bug

#3605 Ensure `HttpClient` does not add `Content-Length` header when the send function does not change `NettyOutbound` or returns `Mono#empty`
  reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
  reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java
Labels: type/bug, warn/regression

#3567 Supports configurable compression level
  docs/modules/ROOT/pages/http-server.adoc
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/Http3StreamBridgeServerHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/BrotliOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/DeflateOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/GzipOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/HttpCompressionOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/HttpCompressionOptionsSpec.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/SnappyOption.java
  reactor-netty-http/src/main/java/reactor/netty/http/server/compression/ZstdOption.java
  reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
  reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Labels: type/enhancement

#3607 Add API for specifying datagram channel strategies per `DnsNameResolver`
  docs/modules/ROOT/pages/http-client.adoc
  docs/modules/ROOT/pages/tcp-client.adoc
  reactor-netty-core/build.gradle
  reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
  reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
Labels: type/enhancement

#3609 Http2Pool: Ensure the permit is returned when the `Borrower` is cancelled
  reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
Labels: type/bug
